# rule identifiers to exclude from running
disabled_rules:
  - trailing_whitespace

# some rules are only opt-in
opt_in_rules:
  - force_unwrapping

# paths to include during linting. `--path` is ignored if present.
included:
  - Forcast

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Carthage
  - Pods
  - Forcast/Constants
  - Forcast/Models

